#!/bin/bash
### BEGIN INIT INFO
# Provides:             Cuckoo 
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         
# Short-Description:    Cuckoo
### END INIT INFO

case "$1" in
  start)
    su cuckoo -c "cd /data/cuckoo/ && screen -d -m ./cuckoo.py"
    su cuckoo -c "cd /data/cuckoo/web && screen -d -m python manage.py runserver 0.0.0.0:8080"
;;
  stop)
    pkill -f "SCREEN -d -m ./cuckoo.py"
    pkill -f "SCREEN -d -m python manage.py runserver 0.0.0.0:8080"
;;

 restart)
   $0 stop
   sleep 30
   $0 start
   ;;

esac
exit 0
